// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRSZRHC6RxAtKuI04siFz4EVb0S4iSqE0',
    appId: '1:78546340541:web:13c3117ff18683c0afc5d4',
    messagingSenderId: '78546340541',
    projectId: 'fit-track-1eb09',
    authDomain: 'fit-track-1eb09.firebaseapp.com',
    storageBucket: 'fit-track-1eb09.appspot.com',
    measurementId: 'G-9RRQRYLT1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxzS1fzotlEMIHJH7nOJupRB4qqlvtmqs',
    appId: '1:78546340541:android:80e2d462f9653f64afc5d4',
    messagingSenderId: '78546340541',
    projectId: 'fit-track-1eb09',
    storageBucket: 'fit-track-1eb09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqgxKOgE2FinefnMbo0Dlz1Dn5aPfUXa4',
    appId: '1:78546340541:ios:f6baae67a777132fafc5d4',
    messagingSenderId: '78546340541',
    projectId: 'fit-track-1eb09',
    storageBucket: 'fit-track-1eb09.appspot.com',
    iosClientId: '78546340541-g0asblvf9essobuvp6meculhavd22p5g.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFlutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqgxKOgE2FinefnMbo0Dlz1Dn5aPfUXa4',
    appId: '1:78546340541:ios:3745c093d09c98c5afc5d4',
    messagingSenderId: '78546340541',
    projectId: 'fit-track-1eb09',
    storageBucket: 'fit-track-1eb09.appspot.com',
    iosClientId: '78546340541-pv21odmat018e4a4jul110gg2n89vv8a.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFlutterProject.RunnerTests',
  );
}
